### ISSUE TITLE
ACL across com_associations

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#7]
#### Introduction

This issue is a placeholder for ACL implementation across the com_associations component.
This issues serves as brainstorm and project planing.

We will needs several types of ACL check:
##### com_associations ACL

com_associations compoent ACL should be used only for the component itself.
- "Configure ACL & Options" (core.admin)
- "Configure Options Only" (core.options)
- "Access Administration Interface" (core.manage)

This ACL options should work exactly like other components.

Task level: Easy

**[Already done!]**
##### com_languages language item ACL **[decided to not go this way]**

This is still in brainstrom, but probaly there will exist a "Use" (core.use) ACL in each language that will disable selecting that language in the language select boxes.

So probably, since the select box are fields generated by the joomla api, this component will not need to do anything.

Task level: Probably none
##### com_`<component>` `<item>` ACL

List and side by side view must respect the com_`<component>` `<item>` ACL

Some examples:
- If a user does not have access to "Access Administration Interface" (core.manage) com_contacts, that component can't appear in the components list of com_associations.
- If a user does not have access to "Edit" (core.edit) com_contacts, the user can't edit the associations of the contacts, but can view them and create new associations.
- If a user does not have access to "Create" (core.create) com_contacts, the user can't create new associations for a particular contact, but can view them and edit them.

Task level: Medium

**Comment by infograf768** [comment]
> This is still in brainstrom, but probaly there will exist a "Use" (core.use) ACL in each language that will disable selecting that language in the language select boxes.

I chose finally `core.permission` and a project PR is here (without the new lang strings)
Look here:
https://github.com/infograf768/joomla-cms/pull/30

**Comment by andrepereiradasilva** [comment]
where we are on this?

**Comment by andrepereiradasilva** [comment]
hi all, basic ACL in the list view for me is the easy part. we already have the item ACL key in the helper 
https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/helpers/associations.php#L135

you just need to call the helper
example for categories in the list helper

``` php
$component = AssociationsHelper::getComponentProperties('com_categories.category|com_content');
$user      = JFactory::getUser();
$userId    = $user->get('id');
// [...]
<?php foreach ($this->items as $i => $item) : ?>
    <?php
    $canCreate  = $user->authorise('core.create',     $component->assetKey . $item->id);
    $canEdit    = $user->authorise('core.edit',       $component->assetKey . $item->id);
    $canCheckin = $user->authorise('core.manage',     $component->component) || $item->checked_out == $userId || $item->checked_out == 0;
    $canChange  = $user->authorise('core.edit.state', $component->assetKey . $item->id) && $canCheckin;
    ?>
    // [...]
<?php endforeach; ?>
```

for the side by  side should be easy too IMHO

**Comment by infograf768** [comment]
Concerning com_language ACL for content language, see my comment here:
https://github.com/infograf768/joomla-cms/pull/30#issuecomment-224499937

**Comment by infograf768** [comment]
And after much thinking
https://github.com/infograf768/joomla-cms/pull/30#issuecomment-234845686

**Comment by infograf768** [comment]
Concerning basic ACL, I do not think we need it in the list view as one should be able to choose any item as reference.
It is in the side by side that it is needed
1. Editing reference item or not (language remaining readonly)
2. Editing/creating Targets (language remaining readonly)

**Comment by jreys** [comment]
Before I continue this task, @andrepereiradasilva suggested I document every case and possible implementation:

list-view: 
- core-edit: already done for reference item, for target prefiled there is still no implementation
- core-manage: edit [associatedcomponent.php](https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/models/fields/associatedcomponent.php) and if it fails, don't add the component to the list
- core-create: after the list-view is improved ( #22 ) only add the new languages if this passes

side-by-side: 
- core-manage: redirect with notice in controller
- core-edit: reference readable but button missing (already done), target will be handled in [itemlanguage.php](https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/models/fields/itemlanguage.php), if can't edit, remove that language + id, it won't add a new item since the existing associations will be broken
- core-create: doesn't apply to reference, target will be handled in [itemlanguage.php](https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/models/fields/itemlanguage.php) , if it fails disable all languages that have ID = 0
- core-create + core-edit disabled on the target: remove access from view? it's useless even if the user can save reference, right?

Am I on the right track? By doing this I avoid JS and I'm not compromising UX.

@alikon @infograf768

**Comment by andrepereiradasilva** [comment]
I will say my opinion in two parts:

> list-view:
> - core-edit: already done for reference item, for target prefiled there is still no implementation
> - core-manage: edit associatedcomponent.php and if it fails, don't add the component to the list
> - core-create: after the list-view is improved ( #22 ) only add the new languages if this passes

You need `core.edit.own` for those components who support it too.

for the rest `list-view` i think i agree.

**Comment by andrepereiradasilva** [comment]
please start implementing the list view ACL while we discuss the side by side

**Comment by andrepereiradasilva** [comment]
closing this
